- hosts: hw1
  tasks:
      - name: Install Nginx
        apt: pkg=nginx state=installed update_cache=true
      - name: Install Git
        apt: pkg=git state=installed update_cache=true
      - name: Git Pull
        git:
            repo: git://github.com/puravshah7495/cse356.git
            dest: /var/www/cse356
            update: yes
            version: master
      - name: Move Hw0.html
        shell: cp /var/www/cse356/hw0.html /usr/share/nginx/html/
      - name: Restart Nginx
        service: name=nginx state=restarted
